name: Java CI with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Build and test with Maven
      - name: Build and test with Maven
        run: mvn -B clean test

      # Step 4: Package application
      - name: Package application
        run: mvn -B package

      # Step 5: Fixed Git operations step
      - name: Update timestamp and push
        run: |
          # Встановлюємо ім'я та email для git
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    # Оновлюємо timestamp
          echo "Workflow executed at $(date)" > workflow_run_timestamp.txt
    
    # Додаємо файл та робимо коміт
           git add workflow_run_timestamp.txt
           git commit -m "CI: Update workflow timestamp [skip ci]" || echo "No changes to commit"
    
    # Примусово оновлюємо гілку
           git pull origin main --rebase --autostash || true
           git push origin main
